version: '3.8'

services:
  godbo-lb:
    image: nginx:mainline
    container_name: godbo-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      internal:

  godbo-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: h-alice/godbo-backend
    container_name: godbo
    hostname: bo
    volumes:
      - ./static:/static
    networks:
      internal:

#    environment:
#      REDIS_ADDR: "redis:6379"

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"

networks:
  internal:
    driver: bridge

