version: '3.8'

services:
  godbo-lb:
    image: nginx:mainline
    container_name: godbo-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      internal:

  godbo-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: h-alice/godbo-backend
    container_name: godbo
    hostname: bo
    volumes:
      - ./static:/static
    networks:
      internal:

  redis:
    image: redis:latest
    networks:
      internal:

networks:
  internal:
    driver: bridge

