version: '3.8'

services:
  godbo-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: h-alice/godbo-backend
    container_name: godbo
    hostname: bo
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app
      - ./static:/static
    networks:
      internal:

  redis:
    image: redis:latest
    networks:
      internal:

networks:
  internal:
    driver: bridge

