version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: h-alice/godbo-backend
    container_name: godbo
    hostname: bo
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app
      - ./static:/static
    networks:
      internal:

#    environment:
#      REDIS_ADDR: "redis:6379"

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"

networks:
  internal:
    driver: bridge

